modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/asd1o1/end-shards/issues"
showAsResourcePack=false

[[mods]]
  modId="endshards"
  version="0.0.1"
  displayName="End Shards"
  updateJSONURL="minecraftforge.net/versions.json"
  displayURL="https://github.com/asd1o1/end-shards"
  logoFile="" #to be added
  authors="amot"
  description="A mod to expand the armour/weapons/tools progression to the end. This new set will be equal to netherrite, but different."

  [[dependencies.endshards]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
  [[dependencies.endshards]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"